[[asset]]
name = "shader"
file = "shader.spv"
type = "shader"
source_file = "shaders/shader.slang"

[[asset]]
name = "shader-debug"
file = "shader.debug.spv"
type = "shader"
source_file = "shaders/shader.slang"
compile_args = ["-g"]

[[asset]]
name = "phoenix-shader"
file = "phoenix.spv"
type = "shader"
source_file = "shaders/phoenix.slang"

[[asset]]
name = "phoenix-shader-debug"
file = "phoenix.debug.spv"
type = "shader"
source_file = "shaders/phoenix.slang"
compile_args = ["-g"]

[[asset]]
name = "duck"
file = "Duck.gltf"
type = "mesh"
source = "https://github.com/KhronosGroup/glTF-Sample-Assets"
author = "Khronos Group"
license = "CC-BY 4.0"
tex_refs = { albedo = "duck-albedo" }

[[asset]]
name = "duck-albedo"
file = "tex/DuckCM.png"
type = "image"
format = "rgba8"
color_space = "srgb"
mips = true
source = "https://github.com/KhronosGroup/glTF-Sample-Assets"
author = "Khronos Group"
license = "CC-BY 4.0"

[[asset]]
name = "statue-tex"
file = "statue-tex.png"
source = "https://pixabay.com/photos/statue-sculpture-figure-1275469/"
author = "Undocumented on Pixabay"
license = "Pixabay Content License https://pixabay.com/service/terms/"
type = "image"
format = "rgba8"
color_space = "srgb"
mips = true
notes = """
Modified by vulkan-tutorial \
(https://docs.vulkan.org/tutorial/latest/06_Texture_mapping/00_Images.html) \
to be 512x512. Incorrectly marked CC0 on the tutorial\
"""
