[[asset]]
name = "shader"
file = "shader.spv"
type = "shader"
source_file = "shaders/shader.slang"

[[asset]]
name = "shader-debug"
file = "shader.debug.spv"
type = "shader"
source_file = "shaders/shader.slang"
compile_args = ["-g"]

[[asset]]
name = "phoenix-shader"
file = "phoenix.spv"
type = "shader"
source_file = "shaders/phoenix.slang"

[[asset]]
name = "phoenix-shader-debug"
file = "phoenix.debug.spv"
type = "shader"
source_file = "shaders/phoenix.slang"
compile_args = ["-g"]

[[asset]]
name = "duck"
file = "Duck.gltf"
type = "mesh"
source = "https://github.com/KhronosGroup/glTF-Sample-Assets"
author = "Khronos Group"
license = "CC-BY 4.0"


[[asset]]
name = "duck-albedo"
file = "tex/DuckCM.png"
type = "image"
format = "bc7"
color_space = "srgb"
mips = true
source = "https://github.com/KhronosGroup/glTF-Sample-Assets"
author = "Khronos Group"
license = "CC-BY 4.0"

[[asset]]
name = "damaged-helmet"
file = "DamagedHelmet.gltf"
type = "mesh"
source = "https://github.com/KhronosGroup/glTF-Sample-Assets"
author = "Khronos Group"
license = "CC-BY 4.0"


[[asset]]
name = "dh-albedo"
file = "tex/Default_albedo.jpg"
type = "image"
format = "bc7"
color_space = "srgb"
mips = true
source = "https://github.com/KhronosGroup/glTF-Sample-Assets"
author = "Khronos Group"
license = "CC-BY 4.0"

[[asset]]
name = "dh-ao"
file = "tex/Default_AO.jpg"
type = "image"
format = "bc7"
color_space = "linear"
mips = true
source = "https://github.com/KhronosGroup/glTF-Sample-Assets"
author = "Khronos Group"
license = "CC-BY 4.0"

[[asset]]
name = "dh-normal"
file = "tex/Default_normal.jpg"
type = "image"
format = "bc5"
color_space = "linear"
mips = true
normal_map = true
source = "https://github.com/KhronosGroup/glTF-Sample-Assets"
author = "Khronos Group"
license = "CC-BY 4.0"

[[asset]]
name = "dh-emissive"
file = "tex/Default_emissive.jpg"
type = "image"
format = "bc7"
color_space = "srgb"
mips = true
source = "https://github.com/KhronosGroup/glTF-Sample-Assets"
author = "Khronos Group"
license = "CC-BY 4.0"

[[asset]]
name = "dh-metal-rough"
file = "tex/Default_metalRoughness.jpg"
type = "image"
format = "bc7"
color_space = "linear"
mips = true
source = "https://github.com/KhronosGroup/glTF-Sample-Assets"
author = "Khronos Group"
license = "CC-BY 4.0"

[[asset]]
name = "flight-helmet"
file = "FlightHelmet.gltf"
type = "mesh"
source = "https://github.com/KhronosGroup/glTF-Sample-Assets"
author = "Khronos Group"
license = "CC-BY 4.0"

[[asset]]
name = "fh-rubber-normal"
file = "tex/fh-rubber-normal.png"
type = "image"
format = "bc5"
color_space = "linear"
mips = true
normal_map = true

[[asset]]
name = "fh-rubber-orm"
file = "tex/fh-rubber-orm.png"
type = "image"
format = "bc7"
color_space = "linear"
mips = true

[[asset]]
name = "fh-rubber-albedo"
file = "tex/fh-rubber-albedo.png"
type = "image"
format = "bc7"
color_space = "srgb"
mips = true

[[asset]]
name = "fh-glass-normal"
file = "tex/fh-glass-normal.png"
type = "image"
format = "bc5"
color_space = "linear"
mips = true
normal_map = true

[[asset]]
name = "fh-glass-orm"
file = "tex/fh-glass-orm.png"
type = "image"
format = "bc7"
color_space = "linear"
mips = true

[[asset]]
name = "fh-glass-albedo"
file = "tex/fh-glass-albedo.png"
type = "image"
format = "bc7"
color_space = "srgb"
mips = true

[[asset]]
name = "fh-metal-normal"
file = "tex/fh-metal-normal.png"
type = "image"
format = "bc5"
color_space = "linear"
mips = true
normal_map = true

[[asset]]
name = "fh-metal-orm"
file = "tex/fh-metal-orm.png"
type = "image"
format = "bc7"
color_space = "linear"
mips = true

[[asset]]
name = "fh-metal-albedo"
file = "tex/fh-metal-albedo.png"
type = "image"
format = "bc7"
color_space = "srgb"
mips = true

[[asset]]
name = "fh-leather-normal"
file = "tex/fh-leather-normal.png"
type = "image"
format = "bc5"
color_space = "linear"
mips = true
normal_map = true

[[asset]]
name = "fh-leather-orm"
file = "tex/fh-leather-orm.png"
type = "image"
format = "bc7"
color_space = "linear"
mips = true

[[asset]]
name = "fh-leather-albedo"
file = "tex/fh-leather-albedo.png"
type = "image"
format = "bc7"
color_space = "srgb"
mips = true

[[asset]]
name = "fh-lenses-normal"
file = "tex/fh-lenses-normal.png"
type = "image"
format = "bc5"
color_space = "linear"
mips = true
normal_map = true

[[asset]]
name = "fh-lenses-orm"
file = "tex/fh-lenses-orm.png"
type = "image"
format = "bc7"
color_space = "linear"
mips = true

[[asset]]
name = "fh-lenses-albedo"
file = "tex/fh-lenses-albedo.png"
type = "image"
format = "bc7"
color_space = "srgb"
mips = true

[[asset]]
name = "statue-tex"
file = "statue-tex.png"
source = "https://pixabay.com/photos/statue-sculpture-figure-1275469/"
author = "Undocumented on Pixabay"
license = "Pixabay Content License https://pixabay.com/service/terms/"
type = "image"
format = "rgba8"
color_space = "srgb"
mips = true
notes = """
Modified by vulkan-tutorial \
(https://docs.vulkan.org/tutorial/latest/06_Texture_mapping/00_Images.html) \
to be 512x512. Incorrectly marked CC0 on the tutorial\
"""
